apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
    - name: http
      nodePort: 32020
      port: {{ .Values.servicePort }}
      targetPort: 8080
      protocol: TCP
  selector:
    app: {{ .Values.app }}
