name: Post Merge SNOW Validation

on:
  pull_request:
    types:
      - closed

jobs:
  check-snow-ticket:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR Description for SNOW Ticket
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const { owner, repo } = context.repo;
            const prNumber = pr.number;
            const prBody = pr.body || "";
            const regex = /(CHG|INC)[0-9]{8}/;

            if (regex.test(prBody)) {
              console.log("✅ Valid SNOW ticket found.");

              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number: prNumber,
                body: "✅ PR merged with a valid SNOW ticket (e.g., CHG/INC12345678)."
              });
            } else {
              console.log("❌ No valid SNOW ticket found.");

              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number: prNumber,
                body: "⚠️ PR was merged **without** a valid SNOW ticket. Please ensure compliance next time (e.g., CHG12345678 or INC12345678)."
              });
            }
