name: Validate PR Comment for SNOW Ticket

on:
  pull_request:
    types: [opened]
jobs:
  check-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Check if comment contains a valid SNOW Ticket ID
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GIT_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            if (!pr) {
              core.setFailed("Error: No PR data found in the payload.");
              return;
            }

            const prBody = pr.body || "";
            const regex = /(CHG|INC)[0-9]{8}/;

            if (!regex.test(prBody)) {
              core.setFailed("Invalid or missing SNOW ticket! PR description must include a valid ticket ID (e.g., CHG12345678 or INC12345678).");
            } else {
              console.log("✅ Valid SNOW ticket found in PR description.");
            }
