name: Debug with SSH

on:
  workflow_dispatch:

jobs:
  debug:
    name: SSH into GitHub Runner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
