name: Debug with SSH

on:
  workflow_dispatch: {}

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Enable SSH access with tmate
        uses: mxschmitt/action-tmate@v3
