name: Debug with SSH

on:
  workflow_dispatch:

jobs:
  debug:
    name: SSH into GitHub Runner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker Buildx (optional)
        uses: docker/setup-buildx-action@v2

      - name: Setup SSH session with tmate
        uses: mxschmitt/action-tmate@v3
